### ISSUE TITLE
iOS 8 Keyboard Extension?

### ISSUE THREAD

**Issue by kermankohli** [tonqa/JustType#2]
Would you be able to create an iOS 8 keyboard extension example project? It'd be really cool!

**Comment by KiranPanesar** [comment]
:+1: For this. Any word, @tonqa?

**Comment by tonqa** [comment]
This would be quite a nice thing. Though, I am currently not able to maintain this project. If you think this can be easily migrated to iOS 8, please feel free to be a maintainer of this code base.

**Comment by KiranPanesar** [comment]
@tonqa I will investigate this over the next few weeks. I'll post any questions I have while I go along – I hope you can help me out!

**Comment by tonqa** [comment]
Of course I can do that, thanks Kiran. Good look.
